import java.util.HashMap;
import java.util.Map;

public class SymbolTable {
    private HashMap<String, String> dictionary;

    public SymbolTable() {
        this.dictionary = new HashMap<>();
        dictionary.put("cada", "each");
        dictionary.put("algunos", "some");
        dictionary.put("cualquier", "any");

        dictionary.put("los", "the");
        dictionary.put("la", "the");
        dictionary.put("las", "the");
        dictionary.put("el", "the");
        dictionary.put("un", "a");
        dictionary.put("una", "a/an");
        dictionary.put("unos", "some");
        dictionary.put("unas", "some");
        dictionary.put("al", "to the");
        dictionary.put("del", "of the");
        dictionary.put("algo", "something");
        dictionary.put("nada", "nothing");
        dictionary.put("ninguno", "none");
        dictionary.put("algún", "some");
        dictionary.put("alguna", "some");

        dictionary.put("aquella", "that");
        dictionary.put("aquellas", "those");
        dictionary.put("estas", "these");
        dictionary.put("esas", "those");
        dictionary.put("aquellos", "those");
        dictionary.put("aquel", "that");
        dictionary.put("estos", "these");
        dictionary.put("esos", "those");
        dictionary.put("ese", "that");
        dictionary.put("este", "this");
        dictionary.put("esto¿a","this");
        dictionary.put("mi", "my");
        dictionary.put("tu", "your");
        dictionary.put("su", "his/her/their");
        dictionary.put("nuestro", "our");
        dictionary.put("mío", "mine");
        dictionary.put("mía", "mine");
        dictionary.put("tuyo", "yours");
        dictionary.put("tuya", "yours");
        dictionary.put("suyo", "his/hers/theirs");
        dictionary.put("suya", "his/hers/theirs");

        dictionary.put("hermosa", "beautiful");
        dictionary.put("grande", "big");
        dictionary.put("pequeño", "small");
        dictionary.put("alto", "tall");
        dictionary.put("bajo", "short");
        dictionary.put("gordo", "fat");
        dictionary.put("delgado", "thin");
        dictionary.put("amigable", "friendly");
        dictionary.put("mezquino", "mean");
        dictionary.put("nuevo", "new");
        dictionary.put("viejo", "old");
        dictionary.put("rojo", "red");
        dictionary.put("azul", "blue");
        dictionary.put("verde", "green");
        dictionary.put("amarillo", "yellow");
        dictionary.put("negro", "black");
        dictionary.put("blanco", "white");
        dictionary.put("morado", "purple");
        dictionary.put("naranja", "orange");
        dictionary.put("inteligente", "intelligent");
        dictionary.put("gracioso", "funny");
        dictionary.put("valiente", "brave");
        dictionary.put("tímido", "shy");
        dictionary.put("perezoso", "lazy");
        dictionary.put("limpio", "clean");
        dictionary.put("sucio", "dirty");
        dictionary.put("caliente", "hot");
        dictionary.put("frío", "cold");
        dictionary.put("mojado", "wet");
        dictionary.put("seco", "dry");
        dictionary.put("rápido", "fast");
        dictionary.put("lento", "slow");
        dictionary.put("joven", "young");
        dictionary.put("rico", "rich");
        dictionary.put("pobre", "poor");
        dictionary.put("bueno", "good");
        dictionary.put("malo", "bad");
        dictionary.put("genial", "great");
        dictionary.put("terrible", "terrible");
        dictionary.put("importante", "important");
        dictionary.put("interesante", "interesting");
        dictionary.put("aburrido", "boring");
        dictionary.put("delicioso", "delicious");
        dictionary.put("repugnante", "disgusting");
        dictionary.put("caro", "expensive");
        dictionary.put("barato", "cheap");
        dictionary.put("difícil", "difficult");
        dictionary.put("fácil", "easy");
        dictionary.put("fuerte", "strong");
        dictionary.put("débil", "weak");
        dictionary.put("feliz", "happy");
        dictionary.put("triste", "sad");
        dictionary.put("emocionado", "excited");
        dictionary.put("calmado", "calm");
        dictionary.put("enojado", "angry");
        dictionary.put("cansado", "tired");
        dictionary.put("energético", "energetic");
        dictionary.put("amable", "kind");
        dictionary.put("cruel", "cruel");
        dictionary.put("brillante", "bright");
        dictionary.put("estúpido", "stupid");
        dictionary.put("honesto", "honest");
        dictionary.put("deshonesto", "dishonest");
        dictionary.put("educado", "polite");
        dictionary.put("maleducado", "rude");
        dictionary.put("generoso", "generous");
        dictionary.put("egoísta", "selfish");
        dictionary.put("paciente", "patient");
        dictionary.put("impaciente", "impatient");
        dictionary.put("orgulloso", "proud");
        dictionary.put("avergonzado", "embarrassed");
        dictionary.put("callado", "quiet");
        dictionary.put("ruidoso", "noisy");
        dictionary.put("tonto", "foolish");
        dictionary.put("serio", "serious");
        dictionary.put("organizado", "organized");
        dictionary.put("desordenado", "messy");
        dictionary.put("creativo", "creative");
        dictionary.put("ordinario", "ordinary");
        dictionary.put("extraordinario", "extraordinary");
        dictionary.put("cuidadoso", "careful");
        dictionary.put("descuidado", "careless");
        dictionary.put("hermoso", "beautiful");
        dictionary.put("feo", "ugly");
        dictionary.put("preciso", "precise");
        dictionary.put("impreciso", "imprecise");
        dictionary.put("popular", "popular");
        dictionary.put("impopular", "unpopular");
        dictionary.put("famoso", "famous");
        dictionary.put("desconocido", "unknown");
        dictionary.put("encantador", "charming");
        dictionary.put("horrible", "horrible");
        dictionary.put("sabio", "wise");
        dictionary.put("hostil", "hostile");
        dictionary.put("servicial", "helpful");
        dictionary.put("inútil", "useless");
        dictionary.put("vívido", "vivid");
        dictionary.put("pálido", "pale");
        dictionary.put("feroz", "fierce");
        dictionary.put("gentil", "kind");
        dictionary.put("dulce", "sweet");
        dictionary.put("agrio", "sour");
        dictionary.put("picante", "spicy");
        dictionary.put("amargo", "bitter");
        dictionary.put("fresco", "fresh");
        dictionary.put("rancio", "stale");
        dictionary.put("moderno", "modern");
        dictionary.put("antiguo", "ancient");
        dictionary.put("normal", "normal");
        dictionary.put("anormal", "abnormal");
        dictionary.put("exitoso", "successful");
        dictionary.put("sin éxito", "unsuccessful");
        dictionary.put("real", "real");
        dictionary.put("falso", "false");
        dictionary.put("abierto", "open");
        dictionary.put("cerrado", "closed");
        dictionary.put("libre", "free");
        dictionary.put("costoso", "expensive");

        dictionary.put("uno", "one");
        dictionary.put("dos", "two");
        dictionary.put("tres", "three");
        dictionary.put("cuatro", "four");
        dictionary.put("cinco", "five");
        dictionary.put("seis", "six");
        dictionary.put("siete", "seven");
        dictionary.put("ocho", "eight");
        dictionary.put("nueve", "nine");
        dictionary.put("diez", "ten");
        dictionary.put("once", "eleven");
        dictionary.put("doce", "twelve");
        dictionary.put("trece", "thirteen");
        dictionary.put("catorce", "fourteen");
        dictionary.put("quince", "fifteen");
        dictionary.put("dieciséis", "sixteen");
        dictionary.put("diecisiete", "seventeen");
        dictionary.put("dieciocho", "eighteen");
        dictionary.put("diecinueve", "nineteen");
        dictionary.put("veinte", "twenty");
        dictionary.put("treinta", "thirty");
        dictionary.put("cuarenta", "forty");
        dictionary.put("cincuenta", "fifty");
        dictionary.put("sesenta", "sixty");
        dictionary.put("setenta", "seventy");
        dictionary.put("ochenta", "eighty");
        dictionary.put("noventa", "ninety");
        dictionary.put("cien", "one hundred");
        dictionary.put("mil", "one thousand");

        dictionary.put("carro", "car");
        dictionary.put("comida", "food");
        dictionary.put("fútbol", "soccer");
        dictionary.put("tiempo", "time");
        dictionary.put("año", "year");
        dictionary.put("gente", "people");
        dictionary.put("manera", "way");
        dictionary.put("día", "day");
        dictionary.put("hombre", "man");
        dictionary.put("gobierno", "government");
        dictionary.put("vida", "life");
        dictionary.put("parte", "part");
        dictionary.put("niño", "child");
        dictionary.put("mundo", "world");
        dictionary.put("escuela", "school");
        dictionary.put("estado", "state");
        dictionary.put("familia", "family");
        dictionary.put("estudiante", "student");
        dictionary.put("grupo", "group");
        dictionary.put("país", "country");
        dictionary.put("problema", "problem");
        dictionary.put("mano", "hand");
        dictionary.put("lugar", "place");
        dictionary.put("caso", "case");
        dictionary.put("semana", "week");
        dictionary.put("compañía", "company");
        dictionary.put("sistema", "system");
        dictionary.put("programa", "program");
        dictionary.put("pregunta", "question");
        dictionary.put("trabajo", "work");
        dictionary.put("número", "number");
        dictionary.put("noche", "night");
        dictionary.put("punto", "point");
        dictionary.put("hogar", "home");
        dictionary.put("agua", "water");
        dictionary.put("habitación", "room");
        dictionary.put("madre", "mother");
        dictionary.put("área", "area");
        dictionary.put("dinero", "money");
        dictionary.put("historia", "history");
        dictionary.put("hecho", "fact");
        dictionary.put("mes", "month");
        dictionary.put("montón", "lot");
        dictionary.put("derecho", "right");
        dictionary.put("estudio", "study");
        dictionary.put("libro", "book");
        dictionary.put("ojo", "eye");
        dictionary.put("palabra", "word");
        dictionary.put("negocio", "business");
        dictionary.put("asunto", "matter");
        dictionary.put("lado", "side");
        dictionary.put("tipo", "type");
        dictionary.put("cabeza", "head");
        dictionary.put("casa", "house");
        dictionary.put("servicio", "service");
        dictionary.put("amigo", "friend");
        dictionary.put("padre", "father");
        dictionary.put("poder", "power");
        dictionary.put("hora", "hour");
        dictionary.put("juego", "game");
        dictionary.put("línea", "line");
        dictionary.put("fin", "end");
        dictionary.put("miembro", "member");
        dictionary.put("ley", "law");
        dictionary.put("coche", "car");
        dictionary.put("ciudad", "city");
        dictionary.put("comunidad", "community");
        dictionary.put("nombre", "name");
        dictionary.put("presidente", "president");
        dictionary.put("equipo", "team");
        dictionary.put("minuto", "minute");
        dictionary.put("idea", "idea");
        dictionary.put("cuerpo", "body");
        dictionary.put("información", "information");
        dictionary.put("espalda", "back");
        dictionary.put("padre/madre", "parent");
        dictionary.put("rostro", "face");
        dictionary.put("otros", "others");
        dictionary.put("nivel", "level");
        dictionary.put("oficina", "office");
        dictionary.put("puerta", "door");
        dictionary.put("salud", "health");
        dictionary.put("persona", "person");
        dictionary.put("arte", "art");
        dictionary.put("guerra", "war");
        dictionary.put("fiesta", "party");
        dictionary.put("resultado", "result");
        dictionary.put("cambio", "change");
        dictionary.put("mañana", "morning");
        dictionary.put("reason", "reason");
        dictionary.put("research", "research");
        dictionary.put("girl", "girl");
        dictionary.put("guy", "guy");
        dictionary.put("moment", "moment");
        dictionary.put("air", "air");
        dictionary.put("teacher", "teacher");
        dictionary.put("force", "force");
        dictionary.put("education", "education");
        dictionary.put("policy", "policy");
        dictionary.put("música", "music");
        dictionary.put("ejemplo", "example");
        dictionary.put("desarrollo", "development");
        dictionary.put("mujer", "woman");
        dictionary.put("chica", "girl");
        dictionary.put("chico", "boy");
        dictionary.put("perro", "dog");
        dictionary.put("gato", "cat");
        dictionary.put("árbol", "tree");
        dictionary.put("flor", "flower");
        dictionary.put("pájaro", "bird");
        dictionary.put("pez", "fish");
        dictionary.put("parque", "park");
        dictionary.put("manzana", "apple");
        dictionary.put("plátano", "banana");
        dictionary.put("uva", "grape");
        dictionary.put("fresa", "strawberry");

        dictionary.put("yo", "i");
        dictionary.put("tú", "you");
        dictionary.put("él", "he");
        dictionary.put("ella", "she");
        dictionary.put("esto", "this");
        dictionary.put("nosotros", "we");
        dictionary.put("ellos", "they");
        dictionary.put("ellas", "they");
        dictionary.put("nosotras", "they");

        dictionary.put("fueron", "were");
        dictionary.put("fué", "was");
        dictionary.put("fuí", "was");
        dictionary.put("estar", "to be");
        dictionary.put("ser", "to be");
        dictionary.put("está", "is");
        dictionary.put("quiere", "wants");
        dictionary.put("podría", "could");
        dictionary.put("debería", "should");
        dictionary.put("debe", "must");
        dictionary.put("debo", "I must");
        dictionary.put("necesito", "I need");
        dictionary.put("necesita", "needs");
        dictionary.put("quiero", "want");
        dictionary.put("tiene", "has");
        dictionary.put("tienen", "have");
        dictionary.put("tengo", "have");
        dictionary.put("estaba", "was");
        dictionary.put("eran", "were");
        dictionary.put("soy", "am");
        dictionary.put("están", "are");
        dictionary.put("son", "are");
        dictionary.put("es", "is");
        dictionary.put("llovió", "rained");
        dictionary.put("comer", "eat");
        dictionary.put("correr", "run");
        dictionary.put("saltar", "jump");
        dictionary.put("jugar", "play");
        dictionary.put("dormir", "sleep");
        dictionary.put("trabajar", "work");
        dictionary.put("leer", "read");
        dictionary.put("escribir", "write");
        dictionary.put("hablar", "speak");
        dictionary.put("caminar", "walk");
        dictionary.put("pensar", "think");
        dictionary.put("llegar", "arrive");
        dictionary.put("asistir", "attend");
        dictionary.put("intentar", "try");
        dictionary.put("evitar", "avoid");
        dictionary.put("empezar", "start");
        dictionary.put("culpar", "blame");
        dictionary.put("tomar prestado", "borrow");
        dictionary.put("romper", "break");
        dictionary.put("construir", "build");
        dictionary.put("llamar", "call");
        dictionary.put("llevar", "carry");
        dictionary.put("cambiar", "change");
        dictionary.put("elegir", "choose");
        dictionary.put("venir", "come");
        dictionary.put("continuar", "continue");
        dictionary.put("cocinar", "cook");
        dictionary.put("corregir", "correct");
        dictionary.put("crear", "create");
        dictionary.put("decidir", "decide");
        dictionary.put("describir", "describe");
        dictionary.put("merecer", "deserve");
        dictionary.put("destruir", "destroy");
        dictionary.put("desarrollar", "develop");
        dictionary.put("descubrir", "discover");
        dictionary.put("dibujar", "draw");
        dictionary.put("dejar caer", "drop");
        dictionary.put("explicar", "explain");
        dictionary.put("fallar", "fail");
        dictionary.put("conducir", "drive");
        dictionary.put("volar", "fly");
        dictionary.put("nadar", "swim");
        dictionary.put("sentir", "feel");
        dictionary.put("ver", "see");
        dictionary.put("escuchar", "listen");
        dictionary.put("oler", "smell");
        dictionary.put("probar", "taste");
        dictionary.put("reír", "laugh");
        dictionary.put("llorar", "cry");
        dictionary.put("gritar", "shout");
        dictionary.put("susurrar", "whisper");
        dictionary.put("encontrar", "find");
        dictionary.put("terminar", "finish");
        dictionary.put("olvidar", "forget");
        dictionary.put("perdonar", "forgive");
        dictionary.put("ir", "go");
        dictionary.put("crecer", "grow");
        dictionary.put("ayudar", "help");
        dictionary.put("esconder", "hide");
        dictionary.put("imaginar", "imagine");
        dictionary.put("incluir", "include");
        dictionary.put("informar", "nform");
        dictionary.put("interesar", "interest");
        dictionary.put("unirse", "join");
        dictionary.put("mantener", "keep");
        dictionary.put("saber", "know");
        dictionary.put("dejar", "leave");
        dictionary.put("aprender", "learn");
        dictionary.put("gustar", "like");
        dictionary.put("perder", "lose");
        dictionary.put("hacer", "make/do");
        dictionary.put("manejar", "drive");
        dictionary.put("significar", "mean");
        dictionary.put("conocer", "to meet/know");
        dictionary.put("extrañar", "miss");
        dictionary.put("mover", "move");
        dictionary.put("necesitar", "need");
        dictionary.put("notar", "notice");
        dictionary.put("abrir", "open");
        dictionary.put("ordenar", "order");
        dictionary.put("poseer", "own");
        dictionary.put("pasar", "pass");
        dictionary.put("pagar", "pay");
        dictionary.put("planificar", "to plan");
        dictionary.put("señalar", "point");
        dictionary.put("preparar", "prepare");
        dictionary.put("proveer", "provide");
        dictionary.put("alcanzar", "reach");
        dictionary.put("recibir", "receive");
        dictionary.put("rechazar", "reject");
        dictionary.put("recordar", "remember");
        dictionary.put("repetir", "repeat");
        dictionary.put("solicitar", "request");
        dictionary.put("descansar", "rest");
        dictionary.put("regresar", "return");
        dictionary.put("guardar", "save");
        dictionary.put("decir", "say");
        dictionary.put("vender", "sell");
        dictionary.put("enviar", "send");
        dictionary.put("establecer", "set");
        dictionary.put("mostrar", "show");
        dictionary.put("firmar", "sign");
        dictionary.put("sonreír", "smile");
        dictionary.put("gastar", "spend");
        dictionary.put("comenzar", "start");
        dictionary.put("quedarse", "stay");
        dictionary.put("detener", "stop");
        dictionary.put("tomar", "take");
        dictionary.put("enseñar", "teach");
        dictionary.put("convertir", "convert");
        dictionary.put("entender", "understand");
        dictionary.put("usar", "use");
        dictionary.put("visitar", "visit");
        dictionary.put("esperar", "wait");
        dictionary.put("querer", "want");

        dictionary.put("rápidamente", "quickly");
        dictionary.put("lentamente", "slowly");
        dictionary.put("cuidadosamente", "carefully");
        dictionary.put("felizmente", "happily");
        dictionary.put("tristemente", "sadly");
        dictionary.put("a menudo", "often");
        dictionary.put("nunca", "never");
        dictionary.put("siempre", "always");
        dictionary.put("a veces", "sometimes");
        dictionary.put("ayer", "yesterday");
        dictionary.put("hoy", "today");
        dictionary.put("ahora", "now");
        dictionary.put("entonces", "then");
        dictionary.put("casi", "almost");
        dictionary.put("exactamente", "exactly");
        dictionary.put("precisamente", "precisely");
        dictionary.put("completamente", "completely");
        dictionary.put("parcialmente", "partially");
        dictionary.put("frecuentemente", "frequently");
        dictionary.put("rara vez", "rarely");
        dictionary.put("ocasionalmente", "occasionally");
        dictionary.put("anualmente", "annually");
        dictionary.put("diariamente", "daily");
        dictionary.put("semanalmente", "weekly");
        dictionary.put("mensualmente", "monthly");
        dictionary.put("en", "in/on");
        dictionary.put("a", "to");
        dictionary.put("a ","at");
        dictionary.put("desde", "from");
        dictionary.put("con", "with");
        dictionary.put("sin", "without");
        dictionary.put("cerca de", "near");
        dictionary.put("lejos de", "far from");
        dictionary.put("encima de", "above");
        dictionary.put("debajo de", "below");
        dictionary.put("dentro de", "inside");
        dictionary.put("fuera de", "outside");

        dictionary.put("y", "and");
        dictionary.put("o", "or");
        dictionary.put("pero", "but");
        dictionary.put("aún", "yet");
        dictionary.put("ya", "yet");
        dictionary.put("así que", "so");
        dictionary.put("porque", "because");
        dictionary.put("si", "if");
        dictionary.put("a menos que", "unless");

        dictionary.put("guau", "wow");
        dictionary.put("uh-oh", "uh-oh");
        dictionary.put("hola", "hello");
        dictionary.put("ay", "yay");
        dictionary.put("buu", "boo");
        dictionary.put("auch", "ouch");
        dictionary.put("jmm", "hmm");

        dictionary.put(",", ",");
        dictionary.put(".", ".");
        dictionary.put(":", ":");
        dictionary.put(";", ";");
        dictionary.put("!", "!");
        dictionary.put("¡", "!");
        dictionary.put("?", "?");
        dictionary.put("¿", "?");

    }

    public String translateInverse(String word) {
        for (Map.Entry<String, String> entry : dictionary.entrySet()) {
            if (entry.getValue().equalsIgnoreCase(word)) {
                return entry.getKey();
            }
        }
        return word; // Si no se encuentra la traducción, devolver la palabra original
    }


    public String translate(String word) {
        return this.dictionary.getOrDefault(word, word);
    }
}
